"""
Nathan Banek
CSC 119 - section 471
6/5/2021
p1.12
Summary: prints the lyincs to "Next to Me" by the Imagine Dragons.
"""
#Write a program that prints a poem of your choice. 
# If you don’t have a favorite poem, search the Internet for “Emily Dickinson” or “e e cummings”.

print("Next To Me")
print()
print("Imagine Dragons")
print()
print("Something about the way that you walked into my living room")
print("Casually and confident lookin' at the mess I am")
print("But still you, still you want me")
print("Stress lines and cigarettes, politics, and deficits")
print("Late bills and overages, screamin' and hollerin'")
print("But still you, still you want me")
print("Oh, I always let you down")
print("You're shattered on the ground")
print("Still, I find you there")
print("Next to me")
print()
print("And oh, stupid things I do")
print("I'm far from good, it's true")
print("But still, I find you")
print("Next to me")
print()
print("There's something about the way that you always see the pretty view")
print("Overlook the blooded mess, always lookin' effortless")
print("And still you, still you want me")
print("I got no innocence, faith ain't no privilege")
print("I am a deck of cards, vice or a game of hearts")
print("And still you, still you want me")
print("Oh, I always let you down")
print("You're shattered on the ground")
print("Still, I find you there")
print("Next to me")
print()
print("And oh, stupid things I do")
print("I'm far from good, it's true")
print("Still, I find you")
print("Next to me")
print()
print("So thank you for taking a chance on me")
print("I know it isn't easy")
print("But I hope to be worth it")
print("So thank you for taking a chance on me")
print("I know it isn't easy")
print("But I hope to be worth it")
print("Oh, I always let you down (I always let you down)")
print("You're shattered on the ground (shattered on the ground)")
print("But still, I find you there (yea-)")
print("Next to me")
print()
print("And oh, stupid things I do (stupid things we do)")
print("I'm far from good, it's true")
print("Still, I find you")
print("Next to me")